#let blue  = rgb("#0000ff")
#let red   = rgb("#ff0000")
#let green = rgb("#00ff00")
#let font-bold   = ("EB Garamond", "Noto Serif CJK")
#let font-italic = ("Linux Libertine", "Noto Serif CJK")
#let font-normal = ("palatino", "Noto Serif CJK")
#let box-stroke = (paint: red, thickness: 0.8pt, dash: "dashed")
